# Generated by Django 4.2.11 on 2025-03-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_taskers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolistapp.taskers'),
        ),
    ]
